package com.ayuus.mysailinglogbook

// Generated by nmea2log.export_android_constants from nmea2log's app_constants.py and app_settings.py --
// do not edit by hand; change the Python and generate again.

object SharedConstants {
    const val EBL_DIR_NAME = "Actisense"
    const val LOGBOOK_FILE_NAME = "logbook.html"
    val LOG_ERROR_TAGS = listOf("[error]")
    const val LOG_FILE_NAME = "nmea2log.log"
    const val LOG_MAX_LINES = 200000
    const val LOG_REFRESH_INTERVAL_MS = 250
    const val LOG_STRIP_HEIGHT = 150
    const val LOG_TIMESTAMP_REGEX = "^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2} "
    const val LOG_TRIM_TO = 150000
    val LOG_WARNING_TAGS = listOf("[warning]", "[anomaly]", "[geocode]")
    const val SAMPLE_CACHE_FILE_NAME = "sample_cache.pkl"
}

object SharedDefaults {
    const val DEFAULT_MIN_STOP_MINUTES = 10.0
    const val DEFAULT_SFTP_PORT = 22
    const val MINIMUM_MINUTES = 1
    const val MINIMUM_PORT = 1
    val BOOT_INTERVAL_CHOICES = listOf(30, 60, 120, 180)
    const val W2K2_USER = ""
    const val W2K2_PASSWORD = ""
    const val BOAT_NAME = ""
    const val MMSI = ""
    const val CALL_SIGN = ""
    const val AUTO_SYNC_ON_LAUNCH = false
    const val AUTO_PUBLISH_AFTER_BUILD = true
    const val MIN_STOP_MINUTES = 10.0
    const val REST_UPLOAD_URL = ""
    const val REST_UPLOAD_USER = ""
    const val REST_UPLOAD_PASSWORD = ""
    const val SFTP_HOST = ""
    const val SFTP_PORT = 22
    const val SFTP_USER = ""
    const val SFTP_PASSWORD = ""
    const val SFTP_REMOTE_PATH = ""
    const val SFTP_HOST_KEY_FINGERPRINT = ""
    const val BOOT_ROUND_INTERVAL_MINUTES = 60
    const val BOOT_PUBLISH_EVERY_ROUND = false
    const val BOOT_FINAL_ON_HARBOUR = true
    const val BOOT_HARBOUR_STATIONARY_MINUTES = 30
    const val BOOT_HARBOUR_ENGINE_OFF_MINUTES = 10
    const val BOOT_FINAL_ON_LEFT_BOAT = true
    const val BOOT_LEFT_BOAT_MINUTES = 20
    const val BOOT_STOP_AFTER_FINAL = false
    const val BOOT_AUTO_START = false
    const val THEME_MODE = "system"
}
